### ISSUE TITLE
Ambiguous module TieKnot: test suite failure for Allure-0.9.3.2

### ISSUE THREAD

**Issue by DanBurton** [AllureOfTheStars/Allure#96]
As seen on the Stackage build server:

```
Building test suite 'test' for Allure-0.9.3.2..
[1 of 1] Compiling Main             ( test/test.hs, dist/build/test/test-tmp/Main.o )

test/test.hs:9:1: error:
    Ambiguous module name ‘TieKnot’:
      it was found in multiple packages:
      Allure-0.9.3.2 LambdaHack-0.9.3.1
  |
9 | import TieKnot
  | ^^^^^^^^^^^^^^
```

I will mark this as an expected test failure in Stackage until this is resolved.

**Comment by DanBurton** [comment]
I was able to reproduce this locally like so:
(This very roughly mimics what the stackage build server does.)

```bash
# setup on my mac
brew install sdl2
brew install sdl2_TTF
```

```bash
stack unpack Allure-0.9.3.2 && cd Allure-0.9.3.2
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

```yaml
# stack.yaml
resolver: nightly-2019-04-12
extra-deps:
- LambdaHack-0.9.3.1@sha256:d6f6f017a78a1036de9b4822f0621596960b383136858ca0894165bcefebb174

```
